// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
        int sampleSize = Integer.parseInt(args[0]);

        int currentRun = 1;
        int over = 0;
        int under = 0;

        while (currentRun <= sampleSize){
            double genNumber = Math.random();
            if (genNumber > 0.5){
                over +=1;
            }
            else{
                under +=1; 
            }
            currentRun +=1;
        }

        double ratio;
        if (under == 0){
            ratio = 1;
        }
        else{
            ratio = (double)over/under;
        }

        System.out.println("> 0.5: " + over + " times\n<= 0.5: "
                            + under + " times\nRatio: " + ratio);
    }
}
